
-- SANTA CÉCILIA VEÍCULOS — CRM Schema
-- Run this in Supabase SQL Editor

-- 1. Create the 'leads' table
CREATE TABLE IF NOT EXISTS leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT,
    phone TEXT,
    vehicle_interest TEXT,
    vehicle_type TEXT,
    payment_method TEXT,
    when_buy TEXT,
    has_trade TEXT,
    trade_details TEXT,
    stage TEXT DEFAULT 'lead'
);

-- 2. Enable RLS
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- 3. Policies
-- Allow anyone (public/anon) to submit a lead
DROP POLICY IF EXISTS "Allow anon INSERT to leads" ON leads;
CREATE POLICY "Allow anon INSERT to leads" 
ON leads FOR INSERT TO anon, authenticated WITH CHECK (true);

-- Allow admins (authenticated users) to see and manage everything
DROP POLICY IF EXISTS "Allow authenticated ALL on leads" ON leads;
CREATE POLICY "Allow authenticated ALL on leads" 
ON leads FOR ALL TO authenticated USING (auth.uid() IS NOT NULL);
